<?php

namespace WebTFEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Article_StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article_StockRepository extends EntityRepository
{
}
