<?php

namespace WebTFEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BarcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarcodeRepository extends EntityRepository
{
}
