<?php

namespace WebTFEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SaveOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaveOperationRepository extends EntityRepository
{
}
