<?php

namespace WebTFEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Stock_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Stock_UserRepository extends EntityRepository
{
}
