<?php

namespace WebTFE\WebTFEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * itemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itemRepository extends EntityRepository
{
}
