<?php

namespace WebTFE\WebTFEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * item-stockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class item_stockRepository extends EntityRepository
{
}
