<?php

namespace WebTFE\WebTFEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * stockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stockRepository extends EntityRepository
{
}
