<?php

namespace WebTFE\WebTFEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * user_roleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_roleRepository extends EntityRepository
{
}
