webtfe_homepage:
    path:     /hello/{id}
    defaults: { _controller: WebTFEBundle:Default:index }

webtfe_login:
    path:   /login
    methods: GET
    defaults: { _controller: WebTFEBundle:ApiAuth:login }

webtfe_logout:
    path:   /logout
    methods: GET
    defaults: { _controller: WebTFEBundle:ApiAuth:logout }

webtfe_api:
    path: /api
    defaults: { _controller: WebTFEBundle:ApiAuth:index }

webtfe_admin:
    path: /admin
    defaults: { _controller: WebTFEBundle:ApiAuth:admin }
