api_mod_com_homepage:
    path:     /hello/{id}
    defaults: { _controller: WebTFEBundle:Default:index }

api_mod_com_login:
    path:   /login
    methods: GET
    defaults: { _controller: WebTFEBundle:ApiAuth:login }

api_mod_com_logout:
    path:   /logout
    methods: GET
    defaults: { _controller: WebTFEBundle:ApiAuth:logout }

api_mod_com_api:
    path: /api
    defaults: { _controller: WebTFEBundle:ApiAuth:index }

api_mod_com_admin:
    path: /admin
    defaults: { _controller: WebTFEBundle:ApiAuth:admin }