<?php

namespace StockHavenBundle\Repository;

/**
 * barcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class barcodeRepository extends \Doctrine\ORM\EntityRepository
{
}
