<?php

namespace StockHavenBundle\Repository;

/**
 * item_stockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class item_stockRepository extends \Doctrine\ORM\EntityRepository
{
}
