<?php

namespace StockHavenBundle\Repository;

/**
 * operationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class operationRepository extends \Doctrine\ORM\EntityRepository
{
}
