<?php

namespace StockHavenBundle\Repository;

/**
 * postalCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postalCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
