<?php

namespace StockHavenBundle\Repository;

/**
 * saveOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saveOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
