<?php

namespace StockHavenBundle\Repository;

/**
 * storeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class storeRepository extends \Doctrine\ORM\EntityRepository
{
}
