StockHavenBundle\Entity\item_stock:
    type: entity
    table: null
    repositoryClass: StockHavenBundle\Repository\item_stockRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
            nullable: true
    manyToOne:
        itemId:
            targetEntity: item
            joinColumn:
                name: item_id
                referencedColumnName: id
        stockId:
            targetEntity: stock
            joinColumn:
                name: stock_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
